"""add_estimated_stay_to_encounter

Revision ID: 395c2e1f7a4a
Revises: b40995e378ec
Create Date: 2025-10-28 14:25:48.344920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '395c2e1f7a4a'
down_revision = 'b40995e378ec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('encounters', sa.Column('estimated_length_of_stay', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('encounters', 'estimated_length_of_stay')
    # ### end Alembic commands ###
