# app/schemas/patient.py
from pydantic import BaseModel, Field
from typing import Optional
from datetime import date, datetime
from typing import Any, List, Dict
# --- Base Schema (common fields) ---
class PatientBase(BaseModel):
    full_name: str
    date_of_birth: Optional[date] = None
    contact_info: Optional[str] = None

# --- Schema for Creating a Patient (ID is generated by backend) ---
class PatientCreate(PatientBase): # <--- Ensure this class is defined correctly
    pass # Currently has no extra fields beyond PatientBase

# --- Schema for Reading Patient Data ---
class PatientRead(PatientBase):
    id: str
    registration_timestamp: datetime
    created_at: datetime

    class Config:
        from_attributes = True

# --- Schema for Updating Patient Data ---
class PatientUpdate(BaseModel):
    full_name: Optional[str] = None
    date_of_birth: Optional[date] = None
    contact_info: Optional[str] = None